apiVersion: apps/v1
kind: Deployment
metadata:
  name: benim-k8s-app
  labels:
    app: web
spec:
  replicas: 3  # Uygulamadan aynı anda 2 adet canlı kopya (Pod) çalışacak!
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx-web
        image: devarsyf/ilk-uygulamam:BUILD_NUMBER_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe: # Kendi kendini iyileştirme testi (Yaşıyor mu?)
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5 # Pod açıldıktan sonra 5 saniye bekle, sonra test et
          periodSeconds: 5       # Her 5 saniyede bir kontrol et
        readinessProbe: # Trafik alma testi (Hazır mı?)
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

