apiVersion: v1
kind: Service
metadata:
  name: benim-k8s-servis
  labels:
    app: web
spec:
  type: NodePort  # Uygulamayı sanal makinenin bir portundan dışarı açar
  selector:
    app: web      # deployment.yaml'daki 'app: web' etiketli 3 podu bulur
  ports:
    - port: 80       # Servisin iç kapısı
      targetPort: 80 # Pod'ların içindeki Nginx kapısı
      nodePort: 30001 # Tarayıcıdan bağlanacağımız dış kapı (30000-32767 arası)
